# -*- coding: utf-8 -*-
"""testing map.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mYMB6HUzk08qc1mJyBJzCXNvsNpECNfm
"""

import folium
from folium import plugins
import webbrowser
# import pandas as pd


import os
import json

# initialize map
UMMlocation = (24.906650167940374, 67.1382397910178)
map_UMM = folium.Map(location = UMMlocation, width = "75%", zoom_start = 19,max_zoom=20) # max zoom: 18
map_UMM



folium.GeoJson("Khoji\map (3).geojson").add_to(map_UMM)

with open("Khoji\map (3).geojson") as f:
  testWay = json.load(f)
finalPath = {}
for feature in testWay['features']:
    path = feature['geometry']['coordinates']

    key = feature['properties']['Name']
    finalPath[key] = path

# finalPath = list(map(switchPosition,path))
# finalPath
# print(finalPath)
# temporary list for checking. output from shortest path should be used instead of initial
initial = [ 'Pakeeza Juice Centre', 'Pan shop', 'New Bilal Hardware', 'Lucky Autos', 'Panaflex Printing', 'Masha Allah general store', 'One ten communication', 'Subhanallah Medical', 'AlRehman autos']
test = []

for i in initial:
  if i in finalPath:
    test.append([finalPath[i][1],finalPath[i][0]])
# print(test)
folium.plugins.AntPath([test]).add_to(map_UMM)
map_UMM.save("map.html")
webbrowser.open("map.html")